# Nome da aplicação Spring Boot
spring.application.name=skillswap-backend

# URL de conexão com o banco MySQL criado pelo Docker
spring.datasource.url=jdbc:mysql://localhost:3308/skillswap_db

# Usuário do banco definido no docker-compose.yml
spring.datasource.username=root

# Senha do banco definida no docker-compose.yml
spring.datasource.password=root

# Atualiza automaticamente as tabelas do banco conforme as entidades Java
spring.jpa.hibernate.ddl-auto=update

# Mostra no terminal os comandos SQL executados pelo Hibernate/JPA
spring.jpa.show-sql=true

# Formata os comandos SQL no terminal para facilitar a leitura
spring.jpa.properties.hibernate.format_sql=true